### ISSUE TITLE
Understand how you handled the AWX error on job template

### ISSUE THREAD

**Issue by gitsowmiyaa** [kusalindika/ssh-key#1]
Hi,

I would like to understand how you converted your project into scm integrate with BitBucket - to handle the error of running a jib template in AWX. Please help. I am stuck at this part and unable to move forward.

**Comment by kusalindika** [comment]
Hi, 

I have replied to your issue in [here](https://github.com/ansible/awx/issues/6213#issuecomment-601998750),

**Comment by gitsowmiyaa** [comment]
Thank you so much for the detailed steps. It helped me setup my github account.. I am not sure if i can connect my bitbucket as it is my company's engdome .. Anyway, after connecting to my github, my project is able to detect my playbooks but if i run the job template, it is not able to see my host inventory.. the warning i am getting is:

[WARNING]: Could not match supplied host pattern, ignoring: hostgroup1

PLAY [Install nginx] ***********************************************************
12:09:13

skipping: no hosts matched

PLAY RECAP *********************************************************************
12:09:13

But if i run it within my docker it is successful:
bash-4.4# ansible-playbook /var/lib/awx/projects/test/first.yml

PLAY [Install nginx] *************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [host1]
ok: [host2]

TASK [Install nginx] *************************************************************************************************************************************************************************************************************************
ok: [host1]
ok: [host2]

TASK [Start NGiNX] ***************************************************************************************************************************************************************************************************************************
ok: [host2]
ok: [host1]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
host1                      : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
host2                      : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Please let me know you mailing address if we can solve it offline there... Your help is much appreciated!

**Comment by kusalindika** [comment]
Hi gitsowmiyaa, 

Hope you have figured out something to get this back on track. btw, this seems issue with your configuration and not with this repo. 
Anyway you can find me on kusalindikax@gmail.com for any inquiries or clarifications needed. 
Hope to respond quicker. 

Thanks
